name: repo-sync
on:
  schedule:
  - cron:  "*/15 * * * *"
jobs:
  repo-sync:
    runs-on: ubuntu-18.04
    steps:
    - name: Define variables
      run: |
        echo "upstream=sonyxperiadev/device-sony-apollo" >> $GITHUB_ENV
        echo "rebase_base=p-mr1" >> $GITHUB_ENV
        echo "rebase_head=MartinX3/omnirom-9.0_twrp-10.0" >> $GITHUB_ENV
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: ${{ env.rebase_head }}
    - name: Define git author for rebase
      run: |
        git config user.email "nc-duenkekl3@netcologne.de"
        git config user.name "Martin DÃ¼nkelmann"
    - uses: repo-sync/github-sync@v2
      with:
        source_repo: ${{ env.upstream }}
        source_branch: "*"
        destination_branch: "*"
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - run: git rebase origin/${{ env.rebase_base }} ${{ env.rebase_head }}
    - run: git push --force-with-lease
